FROM python:3.10-slim
WORKDIR /app
COPY streamlit_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_app /app
COPY app /app/app
CMD ["streamlit", "run", "streamlit_app.py"]
