FROM python:3.10-slim

WORKDIR /app

COPY app/tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app/app

ENV PYTHONPATH=/app

CMD ["pytest", "app/tests/test_simulate.py", "--maxfail=1", "--disable-warnings", "-q"]
